# Generated by Django 2.2 on 2020-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('title_status', models.CharField(max_length=30)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('vin', models.CharField(max_length=30)),
                ('lot', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
            ],
        ),
    ]
