# Generated by Django 2.2 on 2020-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticSearch', '0002_auto_20200622_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
